;;; DO NOT EDIT THIS FILE -- IT IS GENERATED AUTOMATICALLY BY PORTAGE
;;; -----------------------------------------------------------------


;;; color-theme site-lisp configuration

(add-to-list 'load-path "~/.emacs.d/gentoo/color-theme")
(require 'color-theme)


;;; ibuffer site-lisp configuration

(setq load-path (cons "~/.emacs.d/gentoo/ibuffer" load-path))
(require 'ibuffer)


;;; php-mode site-lisp configuration

(setq load-path (cons "~/.emacs.d/gentoo/php-mode" load-path))
(load-library "php-mode")

;;; emacs site-lisp configuration for pymacs

(add-to-list 'load-path "~/.emacs.d/gentoo/pymacs")

(autoload 'pymacs-load "pymacs" nil t)
(autoload 'pymacs-eval "pymacs" nil t)
(autoload 'pymacs-apply "pymacs")
(autoload 'pymacs-call "pymacs")

;;; redo site-lisp configuration

(add-to-list 'load-path "~/.emacs.d/gentoo/redo")
(require 'redo)

;;; auctex site-lisp configuration

(load "auctex.el" nil t t)

;;; auctex site-lisp configuration, activating preview-latex

(load "preview-latex.el" nil t t)

;;; python-mode site-lisp configuration

(add-to-list 'load-path "~/.emacs.d/gentoo/python-mode")

(autoload 'python-mode "python-mode" "Python editing mode." t)
(autoload 'jython-mode "python-mode" "Python editing mode." t)
(autoload 'py-shell "python-mode" "Start an interactive Python interpreter in another window." t)
(autoload 'doctest-mode "doctest-mode" "Editing mode for Python Doctest examples." t)
(autoload 'py-complete "pycomplete" "Complete a symbol at point using Pymacs." t)

(add-to-list 'auto-mode-alist '("\\.py$" . python-mode))
(add-to-list 'auto-mode-alist '("\\.doctest$" . doctest-mode))

(add-to-list 'interpreter-mode-alist '("python" . python-mode))
(add-to-list 'interpreter-mode-alist '("jython" . jython-mode))
